exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('sources').del()
    .then(() => knex('sources').insert([{
      id: 1,
      water_systems_id: 1,
      source_name: 'First Street Well',
      source_type: 'gw',
      critical_to_operations: 'true',
      treatment: 'true',
      year_constructed: 1999,
      capacity: 100,
      condition: 'great',
      continuous_chlorination: 'false',
    },
    {
      id: 2,
      water_systems_id: 1,
      source_name: 'Main Street Well',
      source_type: 'sw',
      critical_to_operations: 'false',
      treatment: 'false',
      year_constructed: 1985,
      capacity: 35,
      condition: 'poor',
      continuous_chlorination: 'true',
    },
    {
      id: 3,
      water_systems_id: 2,
      source_name: 'Sutter Street Well',
      source_type: 'gw',
      critical_to_operations: 'true',
      treatment: 'true',
      year_constructed: 2010,
      capacity: 1000,
      condition: 'great',
      continuous_chlorination: 'false',
    },
    {
      id: 4,
      water_systems_id: 2,
      source_name: 'Shattuck Street Well',
      source_type: 'gw',
      critical_to_operations: 'false',
      treatment: 'false',
      year_constructed: 1960,
      capacity: 50,
      condition: 'fair',
      continuous_chlorination: 'false',
    },
    {
      id: 5,
      water_systems_id: 2,
      source_name: 'University Street Well',
      source_type: 'sw',
      critical_to_operations: 'false',
      treatment: 'true',
      year_constructed: 1999,
      capacity: 99,
      condition: 'great',
      continuous_chlorination: 'false',
    },
    {
      id: 6,
      water_systems_id: 3,
      source_name: 'Market Street Well',
      source_type: 'gw',
      critical_to_operations: 'true',
      treatment: 'true',
      year_constructed: 1999,
      capacity: 750,
      condition: 'great',
      continuous_chlorination: 'false',
    }]));
};
